# Site settings
title: "Alexander Kazeka. Machine learning engineer: computer vision, NLP, deep neural networks"
description: Alexander Kazeka, data science, data visualization, machine learning, computer vision, natural laguage processing, NLP, deep learning, deep neural networks, deep convolutional networks, LSTM, autoencoder, word vectors, word2vec, Python
baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alexander Kazeka
user_description: "Independent contractor: data analysis, visualization, machine learning, computer vision, NLP, and deep neural networks"
user_title: Machine Learning Engineer
email: alexander.kazeka@gmail.com
# twitter_username: lorem_ipsum
github_username:  kazeka
# gplus_username:  lorem_ipsum

# Google-analytics
# google-analytics:
#   id: ""

exclude: ['package.json', 'src' , 'node_modules']
